spring.application.name=api-dressing
weather.api.key=7d961df1e58a5ffdab4de767fc3a1a62

# H2 in-memory database
# http://localhost:8080/h2-console BDD:jdbc:h2:mem:dressing
spring.datasource.url=jdbc:h2:mem:dressing;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000

# Logs
logging.level.com.example.apidressing.security=DEBUG
